/**
 * Courts list from Data/Courts (pickleball_courts.json).
 * Loaded after data.js; assigns to MOCK.courts so the Courts tab and detail view use this data.
 */
(function () {
  var DEFAULT_IMAGE = "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400";
  var RAW = [
    {
      id: 1,
      name: "Palm Beach Gardens Tennis & Pickleball Center",
      city: "Palm Beach Gardens",
      state: "FL",
      zip: "33418",
      address: "5110 117th Ct N, Palm Beach Gardens, FL 33418",
      latitude: 26.8470494,
      longitude: -80.1109099,
      rating: 4.6,
      rating_count: 196,
      phone: "+1 561-630-1180",
      website: "http://www.pbgfl.com/tennis",
      hours: "Mon-Thu 7:30AM-9PM, Fri 7:30AM-7PM, Sat-Sun 7:30AM-3PM",
      courts: 30,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "30 pickleball courts + 50 tennis courts",
    },
    {
      id: 2,
      name: "City Pickleball WPB",
      city: "West Palm Beach",
      state: "FL",
      zip: "33401",
      address: "1016 Clare Ave, West Palm Beach, FL 33401",
      latitude: 26.7019091,
      longitude: -80.0623109,
      rating: 4.2,
      rating_count: 5,
      phone: "+1 561-223-2042",
      website: null,
      hours: "Mon-Sat 10AM-3AM, Sun 11AM-11PM",
      courts: 3,
      type: "indoor",
      free: false,
      indoor: true,
      notes: "Indoor courts with full bar and restaurant",
    },
    {
      id: 3,
      name: "Lake Lytal Park",
      city: "West Palm Beach",
      state: "FL",
      zip: "33406",
      address: "3645 Lake Lytal Park, West Palm Beach, FL 33406",
      latitude: 26.6750645,
      longitude: -80.0994303,
      rating: 4.5,
      rating_count: 731,
      phone: "+1 561-966-6600",
      website: "http://discover.pbcgov.org/parks/Locations/Lake-Lytal.aspx",
      hours: "Mon-Sun 7AM-7PM",
      courts: null,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "Public park with pickleball courts",
    },
    {
      id: 4,
      name: "Replay Club",
      city: "Boynton Beach",
      state: "FL",
      zip: "33426",
      address: "6600 High Ridge Rd, Boynton Beach, FL 33426",
      latitude: 26.5586193,
      longitude: -80.0746803,
      rating: 4.8,
      rating_count: 97,
      phone: "+1 561-484-7287",
      website: "http://replayclub.com/",
      hours: "Mon-Sat 7AM-10PM, Sun 7AM-7PM",
      courts: null,
      type: "indoor/outdoor",
      free: false,
      indoor: true,
      notes: "Pickleball + padel + gym + bar & food",
    },
    {
      id: 5,
      name: "Caloosa Park Pickleball Courts",
      city: "Boynton Beach",
      state: "FL",
      zip: "33426",
      address: "1300 SW 35th Ave, Boynton Beach, FL 33426",
      latitude: 26.4955375,
      longitude: -80.0822344,
      rating: 4.7,
      rating_count: 43,
      phone: null,
      website: null,
      hours: "Mon-Sun 7AM-7PM",
      courts: 8,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "8 free outdoor courts, friendly vibe, all levels",
    },
    {
      id: 6,
      name: "Delray Beach Pickleball Courts",
      city: "Delray Beach",
      state: "FL",
      zip: "33444",
      address: "201 W Atlantic Ave, Delray Beach, FL 33444",
      latitude: 26.4638338,
      longitude: -80.0754525,
      rating: 4.0,
      rating_count: 20,
      phone: "+1 561-243-7360",
      website: "https://www.delraytennis.com/programs/pickleball/",
      hours: "Mon-Sun 9AM-5PM",
      courts: 8,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "8 courts, open play, high-level competition",
    },
    {
      id: 7,
      name: "Patch Reef Pickleball Center",
      city: "Boca Raton",
      state: "FL",
      zip: "33431",
      address: "2000 Yamato Rd, Boca Raton, FL 33431",
      latitude: 26.3888417,
      longitude: -80.1277076,
      rating: 3.3,
      rating_count: 7,
      phone: "+1 561-367-7079",
      website: "https://mybocapatchreeftennis.com/",
      hours: "Mon-Thu 7:30AM-10PM, Fri 7:30AM-9PM, Sat 7:30AM-6PM, Sun 7:30AM-5PM",
      courts: 18,
      type: "covered outdoor",
      free: false,
      indoor: false,
      notes: "18 covered courts organized by skill level. Uses Playbypoint app",
    },
    {
      id: 8,
      name: "Pickleball Courts (Boca West)",
      city: "Boca Raton",
      state: "FL",
      zip: "33498",
      address: "Boca Raton, FL 33498",
      latitude: 26.3782491,
      longitude: -80.2224747,
      rating: 4.7,
      rating_count: 25,
      phone: null,
      website: null,
      hours: "Mon-Sun 8AM-9PM",
      courts: 6,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "6 free outdoor courts, beginners and advanced split",
    },
    {
      id: 9,
      name: "Hillsboro El Rio Park - Pickleball",
      city: "Boca Raton",
      state: "FL",
      zip: "33486",
      address: "Boca Raton, FL 33486",
      latitude: 26.3291875,
      longitude: -80.0942969,
      rating: 4.5,
      rating_count: 11,
      phone: null,
      website: null,
      hours: null,
      courts: null,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "Clean family-friendly park. Great 3.5+ vibe",
    },
    {
      id: 10,
      name: "Dixson Pickleball Club",
      city: "Deerfield Beach",
      state: "FL",
      zip: "33442",
      address: "1700 S Powerline Rd Bay E, Deerfield Beach, FL 33442",
      latitude: 26.2928315,
      longitude: -80.1517242,
      rating: 5.0,
      rating_count: 46,
      phone: "+1 754-200-1394",
      website: "https://www.dixsonclub.com/",
      hours: "Mon-Thu 8AM-10:30PM, Fri-Sun 8AM-8PM",
      courts: null,
      type: "indoor",
      free: false,
      indoor: true,
      notes: "Indoor AC courts. Clinics, leagues & open play",
    },
    {
      id: 11,
      name: "Diadem Pickleball Complex",
      city: "Coconut Creek",
      state: "FL",
      zip: "33066",
      address: "1000 Coconut Creek Blvd, Coconut Creek, FL 33066",
      latitude: 26.2403441,
      longitude: -80.1718628,
      rating: 4.7,
      rating_count: 234,
      phone: "+1 954-708-1566",
      website: "https://www.diadempickleballcomplex.com/",
      hours: "Mon-Sat 7AM-10PM, Sun 7AM-9PM",
      courts: null,
      type: "indoor",
      free: false,
      indoor: true,
      notes: "Premium indoor AC facility. Open play & clinics",
    },
    {
      id: 12,
      name: "Public Pickleball Courts (Pompano)",
      city: "Pompano Beach",
      state: "FL",
      zip: "33062",
      address: "955 N Federal Hwy, Pompano Beach, FL 33062",
      latitude: 26.242293,
      longitude: -80.1028073,
      rating: 4.7,
      rating_count: 71,
      phone: "+1 954-881-4448",
      website: null,
      hours: "Mon-Sun 5AM-10PM",
      courts: 12,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "12 free public courts. Open very early",
    },
    {
      id: 13,
      name: "Pompano Community Park",
      city: "Pompano Beach",
      state: "FL",
      zip: "33060",
      address: "1660 NE 10th St, Pompano Beach, FL 33060",
      latitude: 26.2403303,
      longitude: -80.1058665,
      rating: 4.6,
      rating_count: 2400,
      phone: "+1 954-786-4600",
      website: "https://parks.pompanobeachfl.gov/parks/park-map-and-list/pompano-beach-community-park",
      hours: "Mon-Sun 7:30AM-10:45PM",
      courts: 24,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "24 courts! Organized paddle-up system",
    },
    {
      id: 14,
      name: "Pickleball Courts at Holiday Park",
      city: "Fort Lauderdale",
      state: "FL",
      zip: "33304",
      address: "1150 G. Harold Martin Dr, Fort Lauderdale, FL 33304",
      latitude: 26.1334101,
      longitude: -80.1329654,
      rating: 4.7,
      rating_count: 49,
      phone: "+1 954-881-4448",
      website: "https://pickleballfortlauderdale.com/",
      hours: "Mon 6:30AM-11:30PM, Tue-Sun 6:30AM-9:30PM",
      courts: 6,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "6 courts in converted hockey rink. King of Court format",
    },
    {
      id: 15,
      name: "The FORT Pickleball",
      city: "Fort Lauderdale",
      state: "FL",
      zip: "33315",
      address: "891 SW 34th St, Fort Lauderdale, FL 33315",
      latitude: 26.0817592,
      longitude: -80.1510102,
      rating: 4.7,
      rating_count: 272,
      phone: "+1 954-222-1965",
      website: "https://playthefort.com/",
      hours: "Mon-Wed 6AM-10PM, Thu-Sat 6AM-11PM, Sun 6AM-10PM",
      courts: 40,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "40 courts! Bar + food. $25 open play",
    },
    {
      id: 16,
      name: "Hollywood Pickleball Courts",
      city: "Hollywood",
      state: "FL",
      zip: "33021",
      address: "850 Knights Rd, Hollywood, FL 33021",
      latitude: 26.0175211,
      longitude: -80.1689798,
      rating: 4.5,
      rating_count: 81,
      phone: "+1 917-301-8309",
      website: "http://www.goodtimepickleball.com/",
      hours: "Mon-Sun 7AM-10PM",
      courts: 9,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "9 courts split by skill level. Dogs welcome",
    },
    {
      id: 17,
      name: "Golden Isles Tennis Center",
      city: "Hallandale Beach",
      state: "FL",
      zip: "33009",
      address: "600 Blue Heron Dr, Hallandale Beach, FL 33009",
      latitude: 25.9827295,
      longitude: -80.1336452,
      rating: 4.5,
      rating_count: 150,
      phone: "+1 954-534-9547",
      website: "http://www.cohb.org/Tennis",
      hours: "Mon-Fri 7AM-9PM, Sat-Sun 7AM-1PM",
      courts: null,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "Pickleball + tennis + kids playground",
    },
    {
      id: 18,
      name: "The Lab Pickleball",
      city: "North Miami",
      state: "FL",
      zip: "33168",
      address: "1255 NW 135th St, North Miami, FL 33168",
      latitude: 25.898494,
      longitude: -80.2219904,
      rating: 4.7,
      rating_count: 24,
      phone: "+1 786-665-2618",
      website: "https://www.thelabpb.com/",
      hours: "Mon-Sat 7AM-11PM, Sun 7AM-8PM",
      courts: 8,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "8 courts, 4.0+ competitive play. Great Miami vibe",
    },
    {
      id: 19,
      name: "Dinko Pickleball Complex Miami",
      city: "Miami",
      state: "FL",
      zip: "33138",
      address: "6301 NE 4th Ave, Miami, FL 33138",
      latitude: 25.8338749,
      longitude: -80.1884655,
      rating: 4.8,
      rating_count: 66,
      phone: "+1 786-409-7828",
      website: "http://www.dinkocomplex.com/",
      hours: "Mon-Tue 7AM-10PM, Wed-Thu 7AM-11PM, Fri 7AM-10PM, Sat-Sun 7AM-11PM",
      courts: 4,
      type: "indoor",
      free: false,
      indoor: true,
      notes: "Indoor AC courts. Welcoming community",
    },
    {
      id: 20,
      name: "Miami Beach Pickleball Courts",
      city: "Miami Beach",
      state: "FL",
      zip: "33140",
      address: "2301 Alton Rd, Miami Beach, FL 33140",
      latitude: 25.8020763,
      longitude: -80.1378048,
      rating: 4.7,
      rating_count: 61,
      phone: null,
      website: null,
      hours: "Mon-Sun 7AM-12AM",
      courts: null,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "Free outdoor courts. Open until midnight",
    },
    {
      id: 21,
      name: "Bryan Park",
      city: "Miami",
      state: "FL",
      zip: "33145",
      address: "2301 SW 13th St, Miami, FL 33145",
      latitude: 25.7608041,
      longitude: -80.2326607,
      rating: 4.6,
      rating_count: 428,
      phone: "+1 305-533-3501",
      website: "https://www.miami.gov/Parks-Public-Places/Parks-Directory/Bryan-Park",
      hours: "Mon-Sun 7AM-8:30PM",
      courts: 4,
      type: "outdoor",
      free: true,
      indoor: false,
      notes: "4 dedicated courts near Coconut Grove",
    },
    {
      id: 22,
      name: "Dink Club Pickleball Courts",
      city: "Miami (Kendall)",
      state: "FL",
      zip: "33176",
      address: "10855 SW 112nd Ave, Miami, FL 33176",
      latitude: 25.6670085,
      longitude: -80.372198,
      rating: 5.0,
      rating_count: 28,
      phone: "+1 305-209-3133",
      website: "https://dinkclub.com/",
      hours: "Mon-Sun 7AM-10PM",
      courts: null,
      type: "outdoor",
      free: false,
      indoor: false,
      notes: "Brand new courts. DUPR events & tournaments",
    },
  ];

  function toAppCourt(row) {
    var parts = [];
    if (row.hours) parts.push(row.hours);
    if (row.notes) parts.push(row.notes);
    if (row.free === true) parts.push("Free");
    var amenities = parts.join(" • ");
    return {
      id: String(row.id),
      name: row.name || "",
      address: row.address || row.city + ", " + row.state + " " + row.zip,
      courts: row.courts != null ? row.courts : 0,
      surface: row.type || "outdoor",
      lights: true,
      distance: "",
      lat: row.latitude != null ? Number(row.latitude) : null,
      lng: row.longitude != null ? Number(row.longitude) : null,
      image: DEFAULT_IMAGE,
      amenities: amenities || "",
      rating: row.rating,
      rating_count: row.rating_count,
      phone: row.phone,
      website: row.website,
      free: row.free,
      indoor: row.indoor,
    };
  }

  var list = RAW.map(toAppCourt);
  if (typeof MOCK !== "undefined") MOCK.courts = list;
})();
