// Mock data for Pickleball Community app (Stitch design)

/** Preset avatar URLs for profile/create-account selection (USA-focused app). */
const AVATAR_OPTIONS = [
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBjcXVDOMD2-VXu2A2iBCoXB5LDaO26iuIAQ-lPQ5JuAZSBXfbCjHboooLZwoj0V76aKbemIc9U3vUI-8p0KZrhhgKYgC9g550o0deo2hlpJz7-1kAOzBlV6QU7ingYnVYzyOWYXFnDDTaIjSUrHn1GSRhsAOqSX_7XMgmKRHLwAp32PGrLiLwx3P_4tC__x1Ufwjvuscmo2YjbG06L7JrxgLbeuUgOsQka1uEzKs4hkv7uRBjtu7DwnnSm__4Jk00ZqqQJ3-rm38U",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDi0hYG5mSi8uhcX2H-MJDLGsraIcYF38DVAuTb7g8IxbqkgT5l0HUCiOrJWig3WE9EBGeFLEy_FG5CPj-rpykTKEd15brOfkm5enAfrcAQ7azzI_e1Xee_nHp4JvEErg2AA_0pTZV-BA-JoxZuNWdXdvCWKOOlIkD2BJqLiDDuXIIgi2M5fBhu2OmZB5iPBXR7W4UpJlOYRPkCLk9prF0cA8aawi3P0-DMGRMt4VZIscZ9LGiI7rro87tLye1Tg_yTwJwNgPtQn50",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCXXLtT_Y0KGbhdus9gvoU03KtjYGtJI1sBxWwN0jp4MxRk7k4majHYGbSTZzalvGsUgZ9sT7uET5iUJywJh3bMTbzorvK8VkBZxEKyDrTG-lZbKOKJURqw1H18dZibnfqpNw_g0GFJqZ2YH1alPfNjY_JTochd6Tgehor6sVFbQ5qYWH5MeOncU8kYEBwiThD-kgG-8W-9W7T_J-cV-qPiwUnMXwQ9VaaTSJfwSho11el-JOeEhFL6bQUdLyEXhCZBX1eesu67JgA",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuC-1ili5Ekj5HFDqmDS_C07NI0uF7KcTFNIVgmxDHwIiFV5uM5AsZA6z9f9L72qyU9wncb4lyEuqu-v6O4wGYJzRhmWllb99EY7enMgl15rn0U9pKe9QVPoXX4ySh3LpZth6MwN08D_TKUC-Cw7YUELNssxhgu07iRWnznDlqFOz2V6-mZE7h6R9oJUpFvjCTIz-lAbrv7lkh56WU9rsRZ3svsRgJbqfKilSWheHky-IWtu9gPNaSRGegyfwo2wYiOMhq5cjg1eN4I",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDWu7uC4WP_m696fkDC-QCau_5yo8e4Gkjh1mrD5FhgTP-3Vyk5tU2LSfspYQVoFgvieFyqBNc5AglIW2oP2GmzP35kfUzfPPGbOTpsiKLZB2xLybIDJz2I_qEYQvKqYEI6EQw3_8Z7NqC_vPBP2deh1zalFaT2Yv2jizpjIWDXnAHpwiS9DFcec7pzhgxTXPHko3TlQqGjCXWrgqz8xfG07JzwsED968LE_3Gz50kqVYJYbf2Rf4kfD-hgBIDqRfs0KLQ3ZDBC3Mc",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCMSYcD8XqFc-WtNQz3Ltu-PLr-_Kn7lXVHKjYOTK1j52S5ahetweuO5x9dqolOl-uF9298vVQ5IZ3H5yFk_1buK7vW5bLWHSwPVeEx_6m1JH1oQH8ly6O2KSZnZePlXq3RSuw9zup8RfIixGBWo2WDpTiisS08wnfQAYJ3CGJuHStiNKmx6D1uqXE5UHFqD_WSLNnMPyhRURoxIRWHQh3RO3Jmu0OiLCTEFDNLklos17lu6euPQt0QTKjgm5no68VnBE1_q0LO5R8",
];

const MOCK = {
  user: {
    name: "Alex Rivers",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBjcXVDOMD2-VXu2A2iBCoXB5LDaO26iuIAQ-lPQ5JuAZSBXfbCjHboooLZwoj0V76aKbemIc9U3vUI-8p0KZrhhgKYgC9g550o0deo2hlpJz7-1kAOzBlV6QU7ingYnVYzyOWYXFnDDTaIjSUrHn1GSRhsAOqSX_7XMgmKRHLwAp32PGrLiLwx3P_4tC__x1Ufwjvuscmo2YjbG06L7JrxgLbeuUgOsQka1uEzKs4hkv7uRBjtu7DwnnSm__4Jk00ZqqQJ3-rm38U",
    location: "Austin, TX",
  },

  events: [
    {
      id: "1",
      title: "Morning Doubles Open",
      level: "Intermediate",
      levelPrimary: true,
      date: "Sat, 9:00 AM",
      venue: "Zilker Park Courts",
      lat: 30.2669,
      lng: -97.7728,
      distance: "1.2 mi",
      format: "Doubles",
      joined: "3/4 joined",
      joinedHighlight: true,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      weather: "72° Sunny",
      weatherIcon: "wb_sunny",
      weatherActive: true,
      hostAvatars: [
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDi0hYG5mSi8uhcX2H-MJDLGsraIcYF38DVAuTb7g8IxbqkgT5l0HUCiOrJWig3WE9EBGeFLEy_FG5CPj-rpykTKEd15brOfkm5enAfrcAQ7azzI_e1Xee_nHp4JvEErg2AA_0pTZV-BA-JoxZuNWdXdvCWKOOlIkD2BJqLiDDuXIIgi2M5fBhu2OmZB5iPBXR7W4UpJlOYRPkCLk9prF0cA8aawi3P0-DMGRMt4VZIscZ9LGiI7rro87tLye1Tg_yTwJwNgPtQn50",
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBIhOLqmkxVLBW5D9Tjk0GnbUzW2b0dVkUNbnkHUL0m5g-eUMl2z-RoBZyQUS09hG-aqvg5k10oHxRpBdkd6nSVjhvjJUHKVJUH_8JvgLpOXRLz4DSGqyhSb01qQyIEgDWCqd5AedUAZww-H0LwSj-9WxQFBh50U_iL0URIcN_M-bmMmgrJRRvLYa2OFbrQ6g3xwxz7oOs7htVQl6larGt-g93kNAJOH217e3wVordB2lQOrj9vrP7wkPgQPaYBE5BaeyVn0lnaDDY",
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAU_76XI0UZnUa7AgY7tS9l4ltk3iPrFkaeWdG1pRk9_YRRCTMcF9ZPNXTmTbH1STmFn0HJ3235MDEYVmG5G5NweS-pOS02UgvwTInJDwzUaUXV-J7kJgwMfRcAgQH3kvQS-FdMcJRakyjudTiEx24Ucr0AmLo7C2M5FjQdeFnizRVN5idJ7UB-_EhosNkp-3e3RLtjTzNYKgBFJ70MvnzdYfetTuzmK8KhOE-z41SQgX4t2YRhHzOL5PQNmr_VXzDZKnLmbiIetIM",
      ],
      extraCount: 1,
      cta: "Join Game",
      ctaPrimary: true,
      opacity: 1,
    },
    {
      id: "2",
      title: "Beginner Drills & Play",
      level: "Beginner",
      levelPrimary: false,
      date: "Sun, 11:30 AM",
      venue: "Austin High Courts",
      lat: 30.2642,
      lng: -97.761,
      distance: "2.8 mi",
      format: "Instructional",
      joined: "8/12 joined",
      joinedHighlight: false,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      weather: "68° Cloudy",
      weatherIcon: "cloud",
      weatherActive: false,
      hostAvatars: [],
      extraCount: 0,
      cta: "Reserve Spot",
      ctaPrimary: false,
      opacity: 0.9,
    },
    {
      id: "3",
      title: "Sunset Singles Match",
      level: "Advanced",
      levelPrimary: true,
      date: "Fri, 6:00 PM",
      venue: "Zilker Park Courts",
      lat: 30.2669,
      lng: -97.7728,
      distance: "1.2 mi",
      format: "Singles",
      joined: "4/4 Players",
      joinedHighlight: false,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBoj5YzGaoGA1Xag9fye6eWlpJ61iMtqQ6j_kNDyiDrcgCraorYbH33ChwsT4qZke-r93uIzs19wq7iWir6nFrwi1cOsHbEOf4iGr6r0oS_CRmzxpWd4fMyi0Bw4NBzmS5783diOaRCLnlKZf6GH6-awkjIWGuLAn5s5zCxjXBQdopio-tC9dpbPDV57yF-AKuBZSf0y0INLtB22oZeLpUulodg0prWers0yU278qJXD1meQeGh4JYP5rKE5wiGRX1ljOPTy0r4ZCg",
      weather: "",
      weatherIcon: "",
      weatherActive: false,
      hostAvatars: [],
      extraCount: 0,
      cta: "View Details",
      ctaPrimary: true,
      opacity: 1,
    },
    {
      id: "4",
      title: "Round Rock Open Play",
      level: "Intermediate",
      levelPrimary: true,
      date: "Sat, 2:00 PM",
      venue: "Round Rock Tennis Center",
      lat: 30.5083,
      lng: -97.6789,
      distance: "22 mi",
      format: "Open Play",
      joined: "6/8 joined",
      joinedHighlight: true,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      weather: "75° Sunny",
      weatherIcon: "wb_sunny",
      weatherActive: true,
      hostAvatars: [],
      extraCount: 0,
      cta: "Join Game",
      ctaPrimary: true,
      opacity: 1,
    },
    {
      id: "5",
      title: "Weekend Mixer Doubles",
      level: "All Levels",
      levelPrimary: false,
      date: "Sun, 10:00 AM",
      venue: "Zilker Park Courts",
      lat: 30.2669,
      lng: -97.7728,
      distance: "1.2 mi",
      format: "Doubles",
      joined: "5/8 joined",
      joinedHighlight: true,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      weather: "70° Partly cloudy",
      weatherIcon: "cloud",
      weatherActive: false,
      hostAvatars: [],
      extraCount: 0,
      cta: "Reserve Spot",
      ctaPrimary: false,
      opacity: 1,
    },
    {
      id: "6",
      title: "Lunch Break Singles",
      level: "Intermediate",
      levelPrimary: true,
      date: "Mon, 12:00 PM",
      venue: "Austin High Courts",
      lat: 30.2642,
      lng: -97.761,
      distance: "2.8 mi",
      format: "Singles",
      joined: "2/2 joined",
      joinedHighlight: false,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBoj5YzGaoGA1Xag9fye6eWlpJ61iMtqQ6j_kNDyiDrcgCraorYbH33ChwsT4qZke-r93uIzs19wq7iWir6nFrwi1cOsHbEOf4iGr6r0oS_CRmzxpWd4fMyi0Bw4NBzmS5783diOaRCLnlKZf6GH6-awkjIWGuLAn5s5zCxjXBQdopio-tC9dpbPDV57yF-AKuBZSf0y0INLtB22oZeLpUulodg0prWers0yU278qJXD1meQeGh4JYP5rKE5wiGRX1ljOPTy0r4ZCg",
      weather: "",
      weatherIcon: "",
      weatherActive: false,
      hostAvatars: [],
      extraCount: 0,
      cta: "View Details",
      ctaPrimary: true,
      opacity: 1,
    },
    {
      id: "7",
      title: "Boca Raton Weekend Open",
      level: "All Levels",
      levelPrimary: false,
      date: "Sat, 8:00 AM",
      venue: "Patch Reef Park",
      lat: 26.3587,
      lng: -80.0831,
      distance: "",
      format: "Doubles",
      joined: "6/8 joined",
      joinedHighlight: true,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      weather: "78° Sunny",
      weatherIcon: "wb_sunny",
      weatherActive: true,
      hostAvatars: [],
      extraCount: 0,
      cta: "Join Game",
      ctaPrimary: true,
      opacity: 1,
    },
  ],

  tournaments: [
    {
      id: "t1",
      title: "Austin Summer Slam",
      date: "Aug 15–16",
      venue: "Zilker Park",
      level: "Open",
      prize: "Trophy + bragging rights",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      registered: 24,
      maxTeams: 32,
    },
    {
      id: "t2",
      title: "Round Rock Doubles Championship",
      date: "Sep 7",
      venue: "Round Rock Tennis Center",
      level: "3.0–4.5",
      prize: "Medals",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      registered: 12,
      maxTeams: 16,
    },
    {
      id: "t3",
      title: "Cedar Park Beginner Bracket",
      date: "Sep 21",
      venue: "Cedar Park Rec Center",
      level: "Beginner",
      prize: "Participation medals",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBoj5YzGaoGA1Xag9fye6eWlpJ61iMtqQ6j_kNDyiDrcgCraorYbH33ChwsT4qZke-r93uIzs19wq7iWir6nFrwi1cOsHbEOf4iGr6r0oS_CRmzxpWd4fMyi0Bw4NBzmS5783diOaRCLnlKZf6GH6-awkjIWGuLAn5s5zCxjXBQdopio-tC9dpbPDV57yF-AKuBZSf0y0INLtB22oZeLpUulodg0prWers0yU278qJXD1meQeGh4JYP5rKE5wiGRX1ljOPTy0r4ZCg",
      registered: 8,
      maxTeams: 16,
    },
    {
      id: "t4",
      title: "Boca Raton Open",
      date: "Oct 12–13",
      venue: "Patch Reef Park",
      level: "Open",
      prize: "Trophy + cash",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      registered: 16,
      maxTeams: 24,
    },
  ],

  eventDetails: {
    1: {
      id: "1",
      title: "Morning Doubles Open",
      level: "Intermediate",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      hostName: "Alex Johnson",
      hostSub: "Event Host • 4.5 DUPR",
      hostAvatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCMSYcD8XqFc-WtNQz3Ltu-PLr-_Kn7lXVHKjYOTK1j52S5ahetweuO5x9dqolOl-uF9298vVQ5IZ3H5yFk_1buK7vW5bLWHSwPVeEx_6m1JH1oQH8ly6O2KSZnZePlXq3RSuw9zup8RfIixGBWo2WDpTiisS08wnfQAYJ3CGJuHStiNKmx6D1uqXE5UHFqD_WSLNnMPyhRURoxIRWHQh3RO3Jmu0OiLCTEFDNLklos17lu6euPQt0QTKjgm5no68VnBE1_q0LO5R8",
      locationName: "Zilker Park Courts, Austin, TX",
      mapImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBB20y2N0iaZXjod5YBXCcN9i_TVmGejXQ-trCTfFyPDbD4n9NjRzdDJLNUqAgjm_wkAXPgQNaqVIKoUqVQ2yBAnc-Y_OC9kl9Z5ZRqq2I0tVa4ObDMHLUiXrRgU0RlO0Hg3rPuma5hQxxn_SbybuwujJbZI8mNeFCyuxp_xRkhcMuY3i7Qwl-rqf66cfLFPJ-8Tnlf3cFvO3nqHOw0Z7OU3kuMB7anBNSxO8ojwmkrXsk0qFfRU5PuMJ4gO_V5LUL299QbPEBXXpc",
      date: "Friday, Oct 20",
      time: "6:00 PM - 8:00 PM",
      playerCount: "4",
      playerAvatars: [
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAxqqFnKG1rGEak0nLmYSlTirxX8OVFTcf5QmYIRLq7bkdppoEpNzyBfRs73CmKTMx1Fmj3_MEldb5wwwPbpwVQEGSivKVpKdZk3Z9807eIKLZ4B4beVtskPZu7KmJqRRk4PXTBvwl92gtCeWSssMKCs1qIN6loHQgBKejJySnwTssPuE-a-JbkNBhE1O5r0R-8gG9fUIcsj34X_M6pssPWHPTIinAboKe-hRIbvCI840c9QYBgdlLqIaG5zyERzpfWWQQs_B3WejU",
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBZLv-GKWyZFQ4kf9fIEIpiLYEOdJiorUyicqEymlPcRXCWgpPZxwlCLoVIVgdqhL0d5EK1vzjXPRuz8mugt3QWBxLXwuyAh84NTRpiSqBifbUbjI6TOJzw5SEoz0zXnfrJUIiNtO-ikvQacRcuLT5sE11TRI2XmvOdGH3pfWaPqzCuTHtlVh4sCMqhTHc0nBZ_ERPBXaSDsRzLl58jZoqtDHF6TFKOqZVUCg61wcQI99y_7kKNGiYAFxwasaEyCpmugfFhylTjc4U",
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAsb-yvZWgdkE9Parou1iL-9tqVZON504mzJ1HMd05Ogfi-Eq3_6XcywBBMpgzgQE9ZxE8T9IWoux3Tx_gFbibRhVyKYpvj8HJRKi4YEq3EP7AdLewdiITolN5N8G5b1a3KLRUatHNjUKGH8QtWLhId-rZqaulEgEqjP3JSEj0J8aWmv9Q6k_gnyVUIomf1j_6kmzpLNaXTnraekTXXhCZx7_7CuCZvq7DzGcifs3cgeiopPUoP8EJBNxkR6UGueALR6CpcBtVjubw",
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAzN3BFl7lDUH2ht33oH-56aMomibb7fUz_0bmsq1URS353SeCDAsf3RbqAhLWgNOD7Km-cYue4h-SRh9m42BFcKxAdQMUob8jL72qhvflQttckfKHZ0D4tlUIvbG9K6zXBPCGWj-o4XhDh6AcnbPxRGrp2xu05_nze2g9NzlKNfpwMGj4wXUldHlQ6SCk7MtFt_gapX_ad1ZE90FXRSvNZVy50wMC4FxO7KtOtjK-pj8f0Qe9zmHYBpr_t-eEY62ntOGQ0Fz3FVLY",
      ],
      description:
        "Looking for a competitive game before dark. Bring your own paddle. We'll be playing on Court 3. Water fountain available nearby. High-intensity matches expected!",
      chatPreview: { name: "Sarah M.", text: "I'm bringing a new set of Franklin X-40s!" },
      chatCount: 12,
    },
    2: {
      id: "2",
      title: "Beginner Drills & Play",
      level: "Beginner",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      hostName: "Jordan Lee",
      hostSub: "Event Host • 3.0 DUPR",
      hostAvatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCXXLtT_Y0KGbhdus9gvoU03KtjYGtJI1sBxWwN0jp4MxRk7k4majHYGbSTZzalvGsUgZ9sT7uET5iUJywJh3bMTbzorvK8VkBZxEKyDrTG-lZbKOKJURqw1H18dZibnfqpNw_g0GFJqZ2YH1alPfNjY_JTochd6Tgehor6sVFbQ5qYWH5MeOncU8kYEBwiThD-kgG-8W-9W7T_J-cV-qPiwUnMXwQ9VaaTSJfwSho11el-JOeEhFL6bQUdLyEXhCZBX1eesu67JgA",
      locationName: "Austin High Courts, Austin, TX",
      mapImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCnjA4H5JTxkSv3WPKWkoo7wPP8clAj2pMk5j_8sQ1M6aSDmNri3NHIdoxUQ8UW_w0skPWDTk8qpVr-cmb67AyJPSb6AUY5BEHeF8vNFLn37L7jAhtlwcjPpbJ0J1_yLg87OedzRjm7Rciq66ZNI0IdT-WnjjR-4w1VrXDbfJyg4oeWXSvnBpALOyRLXD8g7jIbAp7jZSfLqpzIgd4HX-cD1g74NSDdEjpXVCf5iMmGfbg_yZkU0L_qBfCdIJuv9DzyDFLuF7xSoMA",
      date: "Sunday, Oct 21",
      time: "11:30 AM - 1:00 PM",
      playerCount: "12",
      playerAvatars: [],
      description: "Beginner-friendly drills and open play. Paddles available to borrow. No experience needed!",
      chatPreview: { name: "Mike", text: "See you all at 10 AM! Don't forget water." },
      chatCount: 8,
    },
    3: {
      id: "3",
      title: "Sunset Singles Match",
      level: "Advanced",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBoj5YzGaoGA1Xag9fye6eWlpJ61iMtqQ6j_kNDyiDrcgCraorYbH33ChwsT4qZke-r93uIzs19wq7iWir6nFrwi1cOsHbEOf4iGr6r0oS_CRmzxpWd4fMyi0Bw4NBzmS5783diOaRCLnlKZf6GH6-awkjIWGuLAn5s5zCxjXBQdopio-tC9dpbPDV57yF-AKuBZSf0y0INLtB22oZeLpUulodg0prWers0yU278qJXD1meQeGh4JYP5rKE5wiGRX1ljOPTy0r4ZCg",
      hostName: "Alex Johnson",
      hostSub: "Event Host • 4.5 DUPR",
      hostAvatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCMSYcD8XqFc-WtNQz3Ltu-PLr-_Kn7lXVHKjYOTK1j52S5ahetweuO5x9dqolOl-uF9298vVQ5IZ3H5yFk_1buK7vW5bLWHSwPVeEx_6m1JH1oQH8ly6O2KSZnZePlXq3RSuw9zup8RfIixGBWo2WDpTiisS08wnfQAYJ3CGJuHStiNKmx6D1uqXE5UHFqD_WSLNnMPyhRURoxIRWHQh3RO3Jmu0OiLCTEFDNLklos17lu6euPQt0QTKjgm5no68VnBE1_q0LO5R8",
      locationName: "Zilker Park Courts, Austin, TX",
      mapImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBB20y2N0iaZXjod5YBXCcN9i_TVmGejXQ-trCTfFyPDbD4n9NjRzdDJLNUqAgjm_wkAXPgQNaqVIKoUqVQ2yBAnc-Y_OC9kl9Z5ZRqq2I0tVa4ObDMHLUiXrRgU0RlO0Hg3rPuma5hQxxn_SbybuwujJbZI8mNeFCyuxp_xRkhcMuY3i7Qwl-rqf66cfLFPJ-8Tnlf3cFvO3nqHOw0Z7OU3kuMB7anBNSxO8ojwmkrXsk0qFfRU5PuMJ4gO_V5LUL299QbPEBXXpc",
      date: "Friday, Oct 20",
      time: "6:00 PM - 8:00 PM",
      playerCount: "4",
      playerAvatars: [],
      description: "Competitive singles. Bring your own paddle. Court 3.",
      chatPreview: null,
      chatCount: 0,
    },
    4: {
      id: "4",
      title: "Round Rock Open Play",
      level: "Intermediate",
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYpz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      hostName: "Chris Davis",
      hostSub: "Event Host • 4.0 DUPR",
      hostAvatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDi0hYG5mSi8uhcX2H-MJDLGsraIcYF38DVAuTb7g8IxbqkgT5l0HUCiOrJWig3WE9EBGeFLEy_FG5CPj-rpykTKEd15brOfkm5enAfrcAQ7azzI_e1Xee_nHp4JvEErg2AA_0pTZV-BA-JoxZuNWdXdvCWKOOlIkD2BJqLiDDuXIIgi2M5fBhu2OmZB5iPBXR7W4UpJlOYRPkCLk9prF0cA8aawi3P0-DMGRMt4VZIscZ9LGiI7rro87tLye1Tg_yTwJwNgPtQn50",
      locationName: "Round Rock Tennis Center, Round Rock, TX",
      mapImage:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCnjA4H5JTxkSv3WPKWkoo7wPP8clAj2pMk5j_8sQ1M6aSDmNri3NHIdoxUQ8UW_w0skPWDTk8qpVr-cmb67AyJPSb6AUY5BEHeF8vNFLn37L7jAhtlwcjPpbJ0J1_yLg87OedzRjm7Rciq66ZNI0IdT-WnjjR-4w1VrXDbfJyg4oeWXSvnBpALOyRLXD8g7jIbAp7jZSfLqpzIgd4HX-cD1g74NSDdEjpXVCf5iMmGfbg_yZkU0L_qBfCdIJuv9DzyDFLuF7xSoMA",
      date: "Saturday, Oct 22",
      time: "2:00 PM - 4:00 PM",
      playerCount: "8",
      playerAvatars: [],
      description: "Open play for all levels. Bring your paddle and water.",
      chatPreview: { name: "Chris", text: "Courts 1–4 reserved for us." },
      chatCount: 5,
    },
  },

  chats: [
    {
      id: "1",
      eventId: "1",
      title: "Saturday Open Play",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuD_vkk8UgZ8X-mAj7kC1TZxjuwlaqgUSE8lLvaI_b91AP4GIGM6XL_2QkDLIJlF4IatHBGYa03S9rJ4CxCWAt2RdBWfSmrhLUDo7cFafxRqBvR_1GdLPbCsnuqENgVQNRe63LNqmQe4s7k1j7QFpCpqLwSmuZewHL9g-eHn-IlTFwxdIT8A_p-Zb_U0LvVgxalziEjDrPtcrgXiyT-JvIZlJw9AyWDiuXzceLZrJwGhcX1dPmVPfDWaGq6PepBMUYGrORSElj2-GLI",
      lastMessage: "Mike: See you all at 10 AM! Don't forget water.",
      time: "10:45 AM",
      unread: 3,
      active: true,
    },
    {
      id: "2",
      eventId: "2",
      title: "Sunset Tournament",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBzAY5Pv43iGI6avMiIbrV9yyq381stKtiZ3_BHKhRJq7l4zfc4qVleBnBN_bs9g0NvHVT7rOqq_NZsGJHiI3pZFhzr-YEZbyHlcasP1ifHHNS9iMZKtrJjXg7nEYvKDpEtrD2ipn1hjToHqimRoqD8nGrEZg_hAFzSgoYvoRR6h4DnGq7HsnJw6lHfkcHNohR0XJsHMM3TzlPgMr-on3xnwsqZcvjwbGB7zdk2D-p1st3yrb_87dMlxWbRjWA0EpqSiKeJ_bSlvqc",
      lastMessage: "Sarah added a new location to the event.",
      time: "9:12 AM",
      unread: 0,
      active: false,
    },
    {
      id: "3",
      eventId: "1",
      title: "Morning Doubles @ Zilker",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCZ45CErDCyyHLZLxIabNxMjevPgRy-rxXGytZ7AlPxB31YBddiCO9yfVeOqVxzcsv_qcyPlR95U_q-1u03Kkm_Vvl5cnw_3KntgmHrDE_FDhUfixo3araM6G-ip4kjp-Vm0WhEK-kGj0THHn-bjMOaMu-17eQLmwdjSFVHOmUXmmkzkb-wGY1Gxn44XICqmmxxQ07X7VnF_5VglsLg4cFEeM_gFKMQZy7me4KBDoywmhJaEqWSh0O-jj3dy3NW4IivpKZbZIEY_N4",
      lastMessage: "You: Thanks for the feedback on my dink!",
      time: "Yesterday",
      unread: 0,
      active: false,
      read: true,
    },
  ],

  chatMessages: {
    1: [
      {
        id: "m1",
        author: "Alex",
        authorAvatar:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuDfnnj93HcCKrO0oPsZtZ2dvfFBZvzluysSbubfqiQziCdsGUEwAycSyYcPJvVqDTfiDMEgVn7rKPsYahZXT2JYgmM60swoKWtzVhruiP_ScEzvoYLTM5bRPIu0PmCNupX6WZTkx5sn0VJiiE8Mq_0I5v3pYKEIIenMNXX0RZtTuIAQgOHNpCdlFFB45r-quYS1nArsbiG9Ezdzq5hs7VdXIEI283INie2-KMKRPXsEqVEDmZrU9jLayA9yteQRiJpz6gmqo8cAQJQ",
        time: "07:15 AM",
        text: "Are we still on for 8 AM? The courts might be busy given the weather.",
        me: false,
      },
      {
        id: "m2",
        author: "Me",
        authorAvatar:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuCYeDZB7UjkIjJ9jEd2u0HZsumSkos1LaEpQ04fKYdRfJ35c3At6f8UQSsl5zYzpSTm86s2M9CWjoprFI7eICXQMToTbx38NhYgt5oynRBxtak6IzO4g36Wh_367RKJNCDBdDTTqmcAA9QIuLfFa5lL2DQMKJRyhxkA1nVBGChRGqx_CB1oVwbv-xA23gMzYoG94Yh6_10jtWIb6wz7dASmpyZE0SmoGCcYdYZPiPjXcmLE3T7R6lmVJphnkxkRTcOwl4xQLstex0M",
        time: "07:18 AM",
        text: "Yes, I'm heading out now to grab a court! I'll text once I secure one. 🎾",
        me: true,
      },
      {
        id: "m3",
        author: "Jordan",
        authorAvatar:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuBxs0BXbV1FSzwUVg_1auK-0OHeQ0Fcqddex_shoKyTc4hwAgw-hyEqGKiXiTrIDoRwsmHYCaZctQGm7C5srjuFbed8kuH2Cp7mFxsSq1pKVsB85B1pLQxUZu8Qk7pRmoMo0PA0H3km8SLJtBptRqvCNsrhkF6B6Qt31SUO2qkUyKqX1lGTGvBr28L1sbIyV0V32kjnA8qtD1GNXZmC_GYcF29bbm7yPCfHTD_hM6Aqet72QJq0unB3o8dedFSW-vFaSmFJO7UeZhg",
        time: "07:22 AM",
        text: "I'm bringing the extra set of balls and some water bottles.",
        me: false,
      },
      {
        id: "m4",
        author: "Taylor",
        authorAvatar:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuBjIOUDSv0jPXT6RtYbV7Bl36_iGO0yyrN49gTjHAP48_vky1kQHWOXMynyEQ_PxUUmvPW1ztJ0zWmGQmWxhwEZQwmAe06ZlYiaQcmc7sIX30UixS_kp3jYkjoJfinZ8LRGLgmZO8jGUbRjvmjRFwyNEYqaK1O-ebSk8YOjaWxm1a7aS6YvNJgPan3ky8IGlNFbVDrhzNkkhyawp2S7S6tyg1hHW1hQ8RRqw_wb6_pPjRmaYmSz20j8DIE5OjHwjvOc7DIYIj6IEYA",
        time: "07:25 AM",
        text: "Ready to go! See you guys there! 🏓",
        me: false,
        image:
          "https://lh3.googleusercontent.com/aida-public/AB6AXuB0orxsSGPDL1JaD0gFIjmZGNcnTb55aQHG5-rJ7S12zly1rpV-grwR7_xNwjkNkCaWRHU_fYFPshVlCTDczc9odWgvbS7rExMFzwoNA8LMQhUkb56MMmJjquI-CP_Z-y7wco9znQY_fQA-Bg-2qLWSCd56TkhZCMR8xT1-O5AfOuJ5dLZck10FPJYohYuM8J8K_DuwFmws2CFLD71-K3hv21mFf-v4dJEZd8Yjz17zcGaVakgE7DjYXwwDFpabaUGutwd7RWDZ9Oc",
      },
    ],
  },

  courts: [
    {
      id: "1",
      name: "Zilker Park Courts",
      address: "2100 Barton Springs Rd, Austin, TX",
      courts: 8,
      surface: "Concrete",
      lights: true,
      distance: "1.2 mi",
      lat: 30.2669,
      lng: -97.7728,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      amenities: "Restrooms, Water fountain, Parking",
    },
    {
      id: "2",
      name: "Austin High Courts",
      address: "1715 W Cesar Chavez St, Austin, TX",
      courts: 6,
      surface: "Hard court",
      lights: true,
      distance: "2.8 mi",
      lat: 30.2642,
      lng: -97.761,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDZjxHVHFIGKPxWGK8SsoDN7ocdMziQl_z0ad40AZxumD2o9VjWyKv1JwTvRJg4IW4X_ELv7nEqJxVpmgATo6la0ee6un3vmbIvIJ7KaGCXFrfmOxrRmA9GAM7X5JKEQN7gdv02s3u2WtxklKkjMAgy61WHUnxA2-4iS-2plhnOh7Tb443psfx8menDN93Uf9BU2ebJ69DmhHoDVGn2PehAGdLfneWe1JFBXmW1LRIhad_1kRcAHWGkLgArm5My4w10-8k6Ad_DU2k",
      amenities: "Restrooms, Parking, Pro shop nearby",
    },
    {
      id: "3",
      name: "Round Rock Tennis Center",
      address: "3001 N AW Grimes Blvd, Round Rock, TX",
      courts: 12,
      surface: "Hard court",
      lights: true,
      distance: "22 mi",
      lat: 30.5083,
      lng: -97.6789,
      image:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCPdWxN_bN42f4hsLIk5-ZD8imSUI9zkFhpnRRDjMv8W24Y84jSqZ4k2WX_PDDVGnYJft5PDbzImS1MgLn13bk4-5kNPPJ_NHBut5IWhpxIzlLGTU_v26wtucbBzbAMZLg3Ef6DnOpGlzphVrAP_wjzKGc_4cc2drTCjPNU2eb0scFFohiccBl3FQmyEtJaXEqfBb2ivAz7mtJRYyrTy_Db9dYz1UmJ4TtUI2pX_J-IYl0WFZDD_6WLiZ4orpgmCWeqLf6iRwqVCQ",
      amenities: "Restrooms, Water, Parking, Lockers",
    },
  ],

  players: [
    {
      id: "1",
      name: "Alex Rivers",
      age: 28,
      city: "Austin, TX",
      level: "Intermediate",
      levelPrimary: true,
      tagline: "Always down for doubles!",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBhVZLBAp50J9Go-4Aezg4IIBijTKB8Trh1AAbe8pShSNf_xs9R6P8JvHRfAzVAqFia14R7TunTQasydgKbO4SHQZ5xcXWmf87cXS8U90bvKpWq1MocuL7u9Tf113EsjgkuZqwZ4mfOoHlPxvS4THRqXaADq0MbMcl7R4_uDgJRERkT5vS0AmJLzaVf3P44XtGAnmq3fwEciGHmglBbAcHZMcDUqBB59hzy-SzhLOBy-L_ikPT8GcRdTtZQdvBBo7qbmrjry9Pa4NI",
      online: true,
    },
    {
      id: "2",
      name: "Sarah Chen",
      age: 31,
      city: "Round Rock, TX",
      level: "Advanced",
      levelPrimary: false,
      tagline: "Looking for competitive tournament partners.",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuC-1ili5Ekj5HFDqmDS_C07NI0uF7KcTFNIVgmxDHwIiFV5uM5AsZA6z9f9L72qyU9wncb4lyEuqu-v6O4wGYJzRhmWllb99EY7enMgl15rn0U9pKe9QVPoXX4ySh3LpZth6MwN08D_TKUC-Cw7YUELNssxhgu07iRWnznDlqFOz2V6-mZE7h6R9oJUpFvjCTIz-lAbrv7lkh56WU9rsRZ3svsRgJbqfKilSWheHky-IWtu9gPNaSRGegyfwo2wYiOMhq5cjg1eN4I",
      online: false,
    },
    {
      id: "3",
      name: "Jordan Miller",
      age: 24,
      city: "Austin, TX",
      level: "Beginner",
      levelPrimary: true,
      tagline: "Just started! Want to practice basics.",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCXXLtT_Y0KGbhdus9gvoU03KtjYGtJI1sBxWwN0jp4MxRk7k4majHYGbSTZzalvGsUgZ9sT7uET5iUJywJh3bMTbzorvK8VkBZxEKyDrTG-lZbKOKJURqw1H18dZibnfqpNw_g0GFJqZ2YH1alPfNjY_JTochd6Tgehor6sVFbQ5qYWH5MeOncU8kYEBwiThD-kgG-8W-9W7T_J-cV-qPiwUnMXwQ9VaaTSJfwSho11el-JOeEhFL6bQUdLyEXhCZBX1eesu67JgA",
      online: true,
    },
    {
      id: "4",
      name: "Maya Rodriguez",
      age: 29,
      city: "Cedar Park, TX",
      level: "Advanced",
      levelPrimary: false,
      tagline: "Drills or games, I'm ready.",
      avatar:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDWu7uC4WP_m696fkDC-QCau_5yo8e4Gkjh1mrD5FhgTP-3Vyk5tU2LSfspYQVoFgvieFyqBNc5AglIW2oP2GmzP35kfUzfPPGbOTpsiKLZB2xLybIDJz2I_qEYQvKqYEI6EQw3_8Z7NqC_vPBP2deh1zalFaT2Yv2jizpjIWDXnAHpwiS9DFcec7pzhgxTXPHko3TlQqGjCXWrgqz8xfG07JzwsED968LE_3Gz50kqVYJYbf2Rf4kfD-hgBIDqRfs0KLQ3ZDBC3Mc",
      online: true,
    },
  ],
};
